### ISSUE TITLE
Freeze on log page

### ISSUE THREAD

**Issue by MPourjam** [TUM-Core-Facility-Microbiome/IMNGS2-Core-docs#18]
**Describe the bug**
After selection of files to run the log screen only shows "Waiting for logs" and at bottom it shows "Initializing IMNGS2-Core environment: Checking docker image tag"

**Screenshots**
![image](https://github.com/user-attachments/assets/c2343fec-eea9-4ca5-9d5e-ed99e2cf5d04)

**Pipeline Log Files**
None of files below got produced.
1) In the selected base directory, there should be a file named `Pipeline_log.txt`
2) In the selected base directory, there should be a file named `IMNGS2Pipeline_args.yml`

**System**
 - I am using KDE desktop on Ubuntu 24.04

I am using version `0.0.1` with pipeline version of `v0.3.0`

**Comment by zsewa** [comment]
This might be connected to the user not being in the docker group. This shouldn't reoccur after implementing #296.

**Comment by MPourjam** [comment]
The problem was due to improper installation on `docker`. Make sure that the docker is properly installed and ready to be used. 

In your terminal run `docker run hello-world` to make sure docker is working properly on Linux machines.

**Comment by zsewa** [comment]
Checking the docker connection is improved with PR https://github.com/TUM-Core-Facility-Microbiome/IMNGS2-Core/pull/305. When the application can not connect to the docker daemon like when the user was not added to the docker group should now display the help text on failed backend connections.
