### ISSUE TITLE
Analyzing on mounted drives (e.g: USB drive) fails

### ISSUE THREAD

**Issue by MPourjam** [TUM-Core-Facility-Microbiome/IMNGS2-Core-docs#20]
**Describe the bug**
When fastq files are located on a mounted storage volume (in this case USB drive), an error like 2024-10-14 16:20:03,002 - run_imngs2:run_imngs2:729 - ERROR - [Errno 1] **Operation not permitted:** '/base/inputs/001-V1-HFW-CD-Mu_S1_L001_R1_001.fastq.gz' -> '/base/inputs/001-V1-HFW-CD-Mu_S1_L001__processed/20241014_162002/001-V1-HFW-CD-Mu_S1_L001_R1_001.fastq.gz' arises.

The same exact files, but located on a primary windows drive, get processed successfully.

**Pipeline Log Files**

[Pipeline_log.txt](https://github.com/user-attachments/files/17374117/Pipeline_log.txt)

**System**
 - Windows 11

**Comment by zsewa** [comment]
I am closing this as we pushed an update to the pipeline. This should not occur anymore with pipeline v0.3.1+.

The USB drive was FAT32 formatted, which does not support symbolic links. We are now back to copying the files to the preprocessed folder in case the creation of a symlink fails.
